### ISSUE TITLE
How to migrate to Hypersistence Utils 3

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hypersistence-utils#536]
The project name was changed from Hibernate Types to Hypersistence Utils because the scope of the project is much broader now, offering Spring utilities as well.

For this reason, when migrating from the Hibernate Types 2.x to Hypersistence Utils 3.x, you will need to follow these steps:

1. First, you will need to change your Maven or Gradle dependency as illustrated by the [Installation Guide](#installation-guide).
2. Second, you will need to change the package name from `com.vladmihalcea.hibernate` to `io.hypersistence.utils.hibernate`.
3. Third, you will need to change the package name from `com.vladmihalcea.spring` to `io.hypersistence.utils.spring`.

For more details, check out [this article](https://vladmihalcea.com/hibernate-types-hypersistence-utils/) as well.

**Comment by MattVonVielen** [comment]
@vladmihalcea I want to use the latest `hypersistence-utils` in my project. One of my project's dependencies which I cannot currently modify already depends on `hibernate-types` and includes entities compiled against `com.vladmihalcea.hibernate.*` Is there any way for both libraries to coexist on the same classpath and work in a predictable manner?

My first attempt was using maven exclusions on my dependency, but that is not an option; Hibernate will of course fail to initialize with NoClassDefFoundError on the `com.vladmihalcea.hibernate` classes.

**Comment by vladmihalcea** [comment]
The `hibernate-types` branch is no longer maintained, so you will have to migrate entirely to Hypersistence Utils if you plan to use the latest versions.

You could probably use both dependencies at the same time since they use different package names, but it's still best to upgrade all dependencies and benefit from future bug fixing.

**Comment by dmitry-weirdo** [comment]
Should https://github.com/vladmihalcea/hypersistence-utils/issues/519 be fixed with this update + Hibernate 6.2?

**Comment by vladmihalcea** [comment]
@dmitry-weirdo Give it a try and see if it works.

**Comment by dmitry-weirdo** [comment]
@vladmihalcea I tried updating the libary to 

```xml
            <dependency>
                <groupId>io.hypersistence</groupId>
                <artifactId>hypersistence-utils-hibernate-60</artifactId>
                <version>3.3.2</version>
            </dependency>
```

And the issue still persists (not the updated package names)
```java
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
	at org.hibernate.type.EnumType.getAnnotation(EnumType.java:238) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.type.EnumType.getEnumType(EnumType.java:229) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.type.EnumType.setParameterValues(EnumType.java:137) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at io.hypersistence.utils.hibernate.type.basic.PostgreSQLEnumType.setParameterValues(PostgreSQLEnumType.java:46) ~[hypersistence-utils-hibernate-60-3.3.2.jar:?]
	at org.hibernate.mapping.MappingHelper.injectParameters(MappingHelper.java:70) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.boot.model.TypeDefinition.createResolution(TypeDefinition.java:161) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.boot.model.TypeDefinition.createLocalResolution(TypeDefinition.java:299) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.mapping.BasicValue.interpretExplicitlyNamedType(BasicValue.java:681) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.mapping.BasicValue.buildResolution(BasicValue.java:353) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.mapping.BasicValue.resolve(BasicValue.java:315) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.mapping.BasicValue.resolve(BasicValue.java:305) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.lambda$processValueResolvers$4(InFlightMetadataCollectorImpl.java:1767) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at java.util.ArrayList.removeIf(ArrayList.java:1682) ~[?:?]
	at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processValueResolvers(InFlightMetadataCollectorImpl.java:1766) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1752) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.buildMetadataInstance(InFlightMetadataCollectorImpl.java:2292) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:349) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1348) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1419) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:66) ~[spring-orm-6.0.8.jar:6.0.8]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[spring-orm-6.0.8.jar:6.0.8]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[spring-orm-6.0.8.jar:6.0.8]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[spring-orm-6.0.8.jar:6.0.8]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352) ~[spring-orm-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[spring-beans-6.0.8.jar:6.0.8]
	... 19 more
```

❗ However, the spring boot `3.0.6` still depends on the `Hibernate 6.1.7` artifacts:
```xml
+- io.hypersistence:hypersistence-utils-hibernate-60:jar:3.3.2:compile
|  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:4.0.0:compile
|  \- io.hypersistence:hypersistence-tsid:jar:2.0.0:compile

...

+- org.springframework.boot:spring-boot-starter-data-jpa:jar:3.0.6:compile
|  +- org.springframework.boot:spring-boot-starter-aop:jar:3.0.6:compile
|  |  \- org.aspectj:aspectjweaver:jar:1.9.19:compile
|  +- org.springframework.boot:spring-boot-starter-jdbc:jar:3.0.6:compile
|  |  +- com.zaxxer:HikariCP:jar:5.0.1:compile
|  |  \- org.springframework:spring-jdbc:jar:6.0.8:compile
|  +- org.hibernate.orm:hibernate-core:jar:6.1.7.Final:compile
|  |  +- jakarta.persistence:jakarta.persistence-api:jar:3.1.0:compile
|  |  +- jakarta.transaction:jakarta.transaction-api:jar:2.0.1:compile
|  |  +- org.hibernate.common:hibernate-commons-annotations:jar:6.0.6.Final:runtime
|  |  +- org.jboss:jandex:jar:2.4.2.Final:runtime
|  |  +- com.fasterxml:classmate:jar:1.5.1:compile
|  |  +- jakarta.inject:jakarta.inject-api:jar:2.0.0:runtime
|  |  \- org.antlr:antlr4-runtime:jar:4.10.1:runtime

...

+- org.springframework.boot:spring-boot-starter-validation:jar:3.0.6:compile
|  +- org.apache.tomcat.embed:tomcat-embed-el:jar:10.1.8:compile
|  \- org.hibernate.validator:hibernate-validator:jar:8.0.0.Final:compile
|     \- jakarta.validation:jakarta.validation-api:jar:3.0.2:compile

...

+- org.springframework.data:spring-data-envers:jar:3.0.5:compile
|  \- org.hibernate.orm:hibernate-envers:jar:6.1.7.Final:compile
 
```

I am not sure how to update the Hibernate within the same Spring Boot.

**Comment by vladmihalcea** [comment]
As mentioned by that issue, [this is what you need](https://github.com/vladmihalcea/hypersistence-utils/issues/519#issuecomment-1484087814).

**Comment by dmitry-weirdo** [comment]
**Yes, the app seems to finally start with the update to `Spring Boot 3.1.0-RC1`!**

Additional Maven repos I need to add:

```xml
    <repositories>
        <repository>
            <id>repository.spring.milestone</id>
            <name>Spring Milestone Repository</name>
            <url>https://repo.spring.io/milestone</url>
        </repository>

        <repository>
            <id>spring-snapshots</id>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
      ...
      
    </repositories>
```

and 

```xml
    <pluginRepositories>

        <pluginRepository>
            <id>repository.spring.milestone</id>
            <name>Spring Milestone Repository</name>
            <url>https://repo.spring.io/milestone</url>
        </pluginRepository>

        <pluginRepository>
            <id>spring-snapshots</id>
            <url>https://repo.spring.io/snapshot</url>
        </pluginRepository>

        ...
    </pluginRepositories>
```

I also had to change the dialect in my `application.yml`:
```yaml
    database-platform: org.hibernate.dialect.PostgreSQLDialect
```

**Comment by vladmihalcea** [comment]
Great!

**Comment by vedrancu** [comment]
Hi,
I using  following in spingboot project:

```
id"org.springframework.boot" version "3.1.2"
.......
implementation 'io.hypersistence:hypersistence-utils-hibernate-62:3.5.0'
```

When run application getting error:

` Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [file_upload_status] in table [auction_file_metadata]; found [\"shema_name\".\"status_file_upload\" (Types#VARCHAR)], but expecting [file_upload_status (Types#OTHER)]`

'status_file_upload' is Postgres type.    
`TYPE schema_name.status_file_upload AS ENUM ('ONE', 'TWO', 'THREE');
ALTER TABLE some_table ADD file_upload_status  schema_name.status_file_upload;`

corresponding entity has:

	```
@Column(name = "file_upload_status", columnDefinition = "file_upload_status")
	@Enumerated(EnumType.STRING)
	@Type(PostgreSQLEnumType.class)
	private StatusFileUploadEnum statusFileUpload;
```


Any idea for this issue maybe?

**Comment by fenuks** [comment]
I can confirm this. It worked with Spring Boot 2 (hibernate 5.6.15.Final and hibernate-types 2.21.1). After migrating to Spring Boot 3 (hibernate 6.2.6.Final, and hypersistence-utils 3.5.1), I have the same error with schema validation.

**Comment by fenuks** [comment]
I don't know where lies the problem. It might be that it is an issue with hibernate, but since @vedrancu mentioned it here, I thought I can confirm it, and provide a bit more detail. I don't think with Spring, since error is reported by `org.hibernate.tool.schema.spi.SchemaManagementException`, so I suppose it is error caused either by hibernate or hypersistence utils, but unfortunately I am not enough familiar with inner working of hibernate to decide which one it is. I tried to debug it, but so far with no success.

**Comment by fenuks** [comment]
I will ask my employer tomorrow and get in touch with you if they agree to.

**Comment by vedrancu** [comment]
Hi
if there is a bug in library why would any commercial relationship be requested?

**Comment by vladmihalcea** [comment]
@vedrancu This is an OSS library. You are free to fork the library, fix issues, and implement any feature you want. 

However, if you want to outsource all that effort, then you will have to pay the third-party.
