### ISSUE TITLE
Infinite recursion in getByReferenceId

### ISSUE THREAD

**Issue by flozano** [vladmihalcea/hypersistence-utils#552]
hypersistence's BaseJpaRepositoryImpl extends spring-data's SimpleJpaRepository.

getByReferenceId in hypersistence's base JPA delegates to getById method , whereas in its super class (SimpleJpaRepository) getById delegates to getByReferenceId.

```
java.lang.StackOverflowError: null
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getById(SimpleJpaRepository.java:363) ~[spring-data-jpa-2.7.6.jar:2.7.6]
	at io.hypersistence.utils.spring.repository.BaseJpaRepositoryImpl.getReferenceById(BaseJpaRepositoryImpl.java:128) ~[hypersistence-utils-hibernate-55-3.0.1.jar:na]
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getById(SimpleJpaRepository.java:363) ~[spring-data-jpa-2.7.6.jar:2.7.6]
	at io.hypersistence.utils.spring.repository.BaseJpaRepositoryImpl.getReferenceById(BaseJpaRepositoryImpl.java:128) ~[hypersistence-utils-hibernate-55-3.0.1.jar:na]
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getById(SimpleJpaRepository.java:363) ~[spring-data-jpa-2.7.6.jar:2.7.6]
	at io.hypersistence.utils.spring.repository.BaseJpaRepositoryImpl.getReferenceById(BaseJpaRepositoryImpl.java:128) ~[hypersistence-utils-hibernate-55-3.0.1.jar:na]
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getById(SimpleJpaRepository.java:363) ~[spring-data-jpa-2.7.6.jar:2.7.6]
	at io.hypersistence.utils.spring.repository.BaseJpaRepositoryImpl.getReferenceById(BaseJpaRepositoryImpl.java:128) ~[hypersistence-utils-hibernate-55-3.0.1.jar:na]
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getById(SimpleJpaRepository.java:363) ~[spring-data-jpa-2.7.6.jar:2.7.6]

```

io.hypersistence.utils.spring.repository.BaseJpaRepositoryImpl:
```java
    @Override
    public T getReferenceById(ID id) {
        return getById(id);
    }

```

org.springframework.data.jpa.repository.support.SimpleJpaRepository:
```java
	/*
	 * (non-Javadoc)
	 * @see org.springframework.data.jpa.repository.JpaRepository#getById(java.io.Serializable)
	 */
	@Deprecated
	@Override
	public T getById(ID id) {
		return getReferenceById(id);
	}

// ...

	/*
	 * (non-Javadoc)
	 * @see org.springframework.data.jpa.repository.JpaRepository#getReferenceById(java.io.Serializable)
	 */
	@Override
	public T getReferenceById(ID id) {

		Assert.notNull(id, ID_MUST_NOT_BE_NULL);
		return em.getReference(getDomainClass(), id);
	}
```

**Comment by vladmihalcea** [comment]
The current test suite uses Spring Data JPA 2.6.0, and it works fine. Looks like Spring Data JPA 2.7.6 causes this issue, but it's easy to fix.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by vladmihalcea** [comment]
You can check the fix in 3.1.1 as it was released.

**Comment by flozano** [comment]
Yes, it's working, thank you!

**Comment by vladmihalcea** [comment]
You're welcome.
