### ISSUE TITLE
Postgres JSON mapping throwing "class org.hibernate.metamodel.mapping.internal.BasicAttributeMapping cannot be cast to class org.hibernate.sql.ast.tree.from.TableGroupJoinProducer" error

### ISSUE THREAD

**Issue by sivaprasadreddy** [vladmihalcea/hypersistence-utils#557]
I am using SpringBoot 3.0.1 and `io.hypersistence:hypersistence-utils-hibernate-60:3.1.1` with Spring Data JPA and Postgres 15.

My Flyway script:

```
create table posts
(
    id         bigserial not null,
    content    text      not null,
    votes      json,
    created_at timestamp,
    updated_at timestamp,
    primary key (id)
);
```

```
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class Votes {
	private Integer up;
	private Integer down;
}
```

```
@Entity
@Table(name = "posts")
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class Post {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cat_id")
	private Category category;

	@Type(JsonType.class)
	@Column(columnDefinition = "json")
	private Votes votes;
}
```

When I run my app and insert data it worked fine and the `votes` column value is stored as json properly.

```
{"up":0,"down":0}
```

But when I try to retrieve the data it is throwing the following error:

```
java.lang.ClassCastException: class org.hibernate.metamodel.mapping.internal.BasicAttributeMapping cannot be cast to class org.hibernate.sql.ast.tree.from.TableGroupJoinProducer (org.hibernate.metamodel.mapping.internal.BasicAttributeMapping and org.hibernate.sql.ast.tree.from.TableGroupJoinProducer are in unnamed module of loader 'app')
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.consumeAttributeJoin(BaseSqmToSqlAstConverter.java:2853) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.consumeExplicitJoin(BaseSqmToSqlAstConverter.java:2751) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.lambda$consumeExplicitJoins$42(BaseSqmToSqlAstConverter.java:2735) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.hibernate.query.sqm.tree.domain.AbstractSqmFrom.visitSqmJoins(AbstractSqmFrom.java:260) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.consumeExplicitJoins(BaseSqmToSqlAstConverter.java:2731) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.consumeJoins(BaseSqmToSqlAstConverter.java:2625) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.consumeFromClauseRoot(BaseSqmToSqlAstConverter.java:2600) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	
```

**Reproducer:**
GitHub repo: https://github.com/sivaprasadreddy/jpa-playground

You can start the postgres using docker-compose and run the app. When you navigate to http://localhost:8080/c/java you can see error in UI and in console as well.

**Comment by vladmihalcea** [comment]
The `votes` property is a basic attribute, but you are JOIN it as if it's an association.

So instead of:

````
@Query(value = "select p from Post p join p.category c left join fetch p.votes where c.slug=?1",
			countQuery = "select count(p) from Post p join p.category c where c.slug=?1")
	Page<Post> findPostsByCategorySlug(String categorySlug, Pageable pageable);
````

You should have:

````
@Query(value = "select p from Post p join p.category c where c.slug=?1",
			countQuery = "select count(p) from Post p join p.category c where c.slug=?1")
	Page<Post> findPostsByCategorySlug(String categorySlug, Pageable pageable);
````

That's it.

**Comment by sivaprasadreddy** [comment]
Yeah, that's the issue. Thank you @vladmihalcea

**Comment by vladmihalcea** [comment]
You're welcome. I'm glad I could help.
