### ISSUE TITLE
ListArrayTypeDescriptor doesn't support Spring JPA Projections

### ISSUE THREAD

**Issue by SergeiKhmelevSPA** [vladmihalcea/hypersistence-utils#562]
The issue occurred when I was upgrading from `hibernate-types-55 (2.19.2)` to `hypersistence-utils-hibernate-55 (3.1.1)`.

A query that uses a projection couldn't create a list:
```
java.lang.NullPointerException
	at java.base/java.lang.Class.isAssignableFrom(Native Method)
	at io.hypersistence.utils.hibernate.type.array.internal.ListArrayTypeDescriptor.newPropertyCollectionInstance(ListArrayTypeDescriptor.java:154)
	at io.hypersistence.utils.hibernate.type.array.internal.ListArrayTypeDescriptor.wrap(ListArrayTypeDescriptor.java:77)
	at io.hypersistence.utils.hibernate.type.array.internal.ArraySqlTypeDescriptor$2.doExtract(ArraySqlTypeDescriptor.java:55)
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257)
	...
org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.doExecute(JpaQueryExecution.java:179)
```

PR to reproduce: https://github.com/vladmihalcea/hypersistence-utils/pull/563

**Comment by vladmihalcea** [comment]
Fixed.
