### ISSUE TITLE
HQL Query on @Type field throwing Exception: [java.lang.String] did not match parameter type [java.util.Map (n/a)]

### ISSUE THREAD

**Issue by michaelhaessig** [vladmihalcea/hypersistence-utils#585]
I'm pretty sure something on my setup is not right, i would expect the following HQL query to work; 

In my model i've added the ```@Type``` Annotation on the Map field that is stored as JSON on a String column in the database:

```java
  @Type(JsonType.class)
  @Column(name = "product_title")
  private Map<String,String> title;
```

I've also tried the ```@Type(JsonStringType.class)``` Annotation (same result). 

Executing the following HQL throws an exception:

```java
  return entityManager.createQuery("select p from Product p where p.title = :title and p.state = 1")
                .setParameter("title", "Test")
                .getResultList();
```

This is the main part of the stacktrace:
```java
java.lang.IllegalArgumentException: Argument [Test] of type [java.lang.String] did not match parameter type [java.util.Map (n/a)]

	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:84)
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:31)
	at org.hibernate.query.internal.QueryParameterBindingImpl.validate(QueryParameterBindingImpl.java:339)
	at org.hibernate.query.internal.QueryParameterBindingImpl.setBindValue(QueryParameterBindingImpl.java:129)
	at org.hibernate.query.spi.AbstractCommonQueryContract.setParameter(AbstractCommonQueryContract.java:860)
	at org.hibernate.query.spi.AbstractSelectionQuery.setParameter(AbstractSelectionQuery.java:708)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.setParameter(QuerySqmImpl.java:1222)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:401)
```

As far as I know it should be possible to query the field with a String parameter  (findById, persist is working using the JSON type). **Any hints on what might be missing on my setup is greatly appreciated!**

Library versions i'm using:

spring: **6.0.2**
spring-boot-starter-data-jpa: **3.0**
hibernate-core: **6.1.5.Final**
hypersistence-utils-hibernate-60: **3.2.0**

**Comment by vladmihalcea** [comment]
The entity attribute is `Msp`, but you are binding a String.

So, instead of:

````
entityManager.createQuery("select p from Product p where p.title = :title and p.state = 1")
                .setParameter("title", "Test")
                .getResultList();
````

It should be:

````
Map<String, String> myMap = ...;


entityManager.createQuery("select p from Product p where p.title = :title and p.state = 1")
                .setParameter("title", myMap)
                .getResultList();
````

**Comment by michaelhaessig** [comment]
@vladmihalcea  thanks for the quick answer, really appricate it!

I was actually using the spring data specification in combination with a like 

````java
 Specification<Product> spec = ((root, query, cb) -> cb.like(root.get("title"), "%Test%"));

````


I've previously tried providing a map, but the *like* method params only accept strings.


Same with HQL like does not seem to be supported.  **Is there no way to generate a like query using the JSON types?**
````java
select p from Product p where p.title like :title and p.state = 1
````


But as pointed out with equal the map is accepted:
````java
 Specification<Product> spec = ((root, query, cb) -> cb.equal(root.get("title"), map));

````


Using a Map as a parameter i can get the query to execute, but strangely i'm now getting what seems to be a unicode exception:
```java
by: java.sql.SQLException: Invalid utf8 character string: 'ACED00'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
```

Again any hint on what might be the issue here would be much appreciated, thanks again for your time!

**Comment by vladmihalcea** [comment]
You can use a [custom Repository](https://vladmihalcea.com/custom-spring-data-repository/) and generate the LIKE query any way you want since you have full control over the JPQL query.

Just because Spring Data JPA offers some abstractions, it doesn't mean you should limit yourself to the limited Specification API. A custom Repository is the most flexible solution.

**Comment by michaelhaessig** [comment]
Thanks for the guidance.

Using  HQL for executing a query using LIKE works!

I also found this solution to make it work on the Specification/Critera API,  note the cast with **.as(String.class)**

````java
 Specification<Product> spec = ((root, query, cb) -> cb.like(root.get("title").as(String.class), SQLHelper.likeParam(search)));
````

This generates a cast in the SQL:
````SQL
cast(p1_0.product_title as char) like '%Test%' 
````
which is not ideal, it causes the index to be skipped, however as our LIKE query does not use the index anyways it's a valid solution.

Thanks again for the help and the great library!

**Comment by vladmihalcea** [comment]
You're welcome. If you liked Hypersistence Utils, you're going to love [Hypersistence Optimizer](https://vladmihalcea.com/hypersistence-optimizer/).
