### ISSUE TITLE
ListArrayType isn't working when registered on Dialect config class.

### ISSUE THREAD

**Issue by adolfo-cia** [vladmihalcea/hypersistence-utils#600]
In our service we have two ways for querying, one through the classic way using entities that involves using fully the ORM/repositories/criteriaQuery/etc and the other one just plain native SQL.

We use the **ListArrayType** at entity fields like

```java
@Column(name = "range_texts", length = 500)
@Type(type = "list-array")
private List<String> rangeTexts;

@Column(name = "range_values")
@Type(type = "list-array")
private List<Integer> rangeValues;
```
and that's working well.

But we tried to use native queries doing a select on a column which is an array:
```java
List<Object[]> rawResult = getCurrentSession().createSQLQuery(queryStringBuilder.toString())
                    .getResultList();
```
and in the dialect config class we set:
```java
this.registerHibernateType(Types.ARRAY, ListArrayType.class.getName());
```
Then it throws a NullPointerExcepciton on :
```
Caused by: java.lang.NullPointerException: null
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.vladmihalcea.hibernate.util.ReflectionUtils.getClass(ReflectionUtils.java:484)
	at com.vladmihalcea.hibernate.type.array.internal.ListArrayTypeDescriptor.setParameterValues(ListArrayTypeDescriptor.java:102)
	at com.vladmihalcea.hibernate.type.array.internal.AbstractArrayType.setParameterValues(AbstractArrayType.java:42)
	at org.hibernate.type.TypeFactory.injectParameters(TypeFactory.java:123)
	at org.hibernate.type.TypeFactory.type(TypeFactory.java:108)
```
The `parameters` argument passed to the `setParamterValues` is empty, so that ends up causing the null pointer.
If we set the dialect with **StringArrayType**, works fine, but we can't handle another scenario where we have int array for example.

Another weird scenario is that when **ListArrayType** is used like this:
```java
List<Object[]> rawResult = getCurrentSession().createSQLQuery(queryStringBuilder.toString())
                    .unwrap(org.hibernate.query.NativeQuery.class)
                    .addScalar("member_fundings_eid", ListArrayType.INSTANCE)
                    .getResultList();
```
It works just fine. I debugged it and the `setParameterValues` function is never executed. That's why I think doesn't produce an error.

Any thoughts?

Thanks.

**Comment by vladmihalcea** [comment]
ListArrayType is way to specific to register it globally because it needs to know the underlying element type.

That's why it works when you use it for mapping columns. The property type will be sent to the associated ListArrayType.

So, you already know the solution. You need to use `addScalar` for each native SQL query that fetches arrays.

**Comment by adolfo-cia** [comment]
Thanks for the quick reply @vladmihalcea ! 
Didn't know about that specifics of ListArrayType, thanks for clarifying. 
Ok, so we go with the solution of setting globally in dialect StringArrayType, and if we want to for example select a column that has int array then we specifically use `.addScalar`

Thanks!

**Comment by vladmihalcea** [comment]
You're welcome.
