### ISSUE TITLE
Hibernate 6.0/6.1 generics: Error Named type [interface java.util.List] did not implement BasicType nor UserType

### ISSUE THREAD

**Issue by CristianPi** [vladmihalcea/hypersistence-utils#618]
The code example

```java
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@MappedSuperclass
public abstract class Diff<Parent, Lines extends DiffLine<?, ?>> extends AbstractEntity {

    @Type(JsonType.class)
    @Column(columnDefinition = "json")
    private List<Lines> lines = new LinkedList<>();

}
```

```bash
caused by: java.lang.IllegalArgumentException: Named type [interface java.util.List] did not implement BasicType nor UserType
	at org.hibernate.boot.model.TypeDefinition.createResolution(TypeDefinition.java:271)
	at org.hibernate.boot.model.TypeDefinition.createResolution(TypeDefinition.java:121)
	at org.hibernate.boot.model.TypeDefinition.resolve(TypeDefinition.java:106)
	at org.hibernate.mapping.BasicValue.interpretExplicitlyNamedType(BasicValue.java:671)
	at org.hibernate.mapping.BasicValue.buildResolution(BasicValue.java:353)
	at org.hibernate.mapping.BasicValue.resolve(BasicValue.java:315)
	at org.hibernate.mapping.BasicValue.getType(BasicValue.java:293)
	at org.hibernate.metamodel.internal.AttributeFactory.determineAttributeMetadata(AttributeFactory.java:375)
	at org.hibernate.metamodel.internal.AttributeFactory.buildAttribute(AttributeFactory.java:111)
	at org.hibernate.metamodel.internal.AttributeFactory.buildAttribute(AttributeFactory.java:96)
	at org.hibernate.metamodel.internal.MetadataContext.wrapUp(MetadataContext.java:332)
	at org.hibernate.metamodel.model.domain.internal.JpaMetamodelImpl.processJpa(JpaMetamodelImpl.java:504)
	at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.finishInitialization(MappingMetamodelImpl.java:244)
	at org.hibernate.metamodel.internal.RuntimeMetamodelsImpl.finishInitialization(RuntimeMetamodelsImpl.java:60)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:415)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1423)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:66)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
	... 97 more
```

Using **ListArrayType** the code crash with:

```bash
Caused by: java.lang.IllegalArgumentException: java.lang.ClassNotFoundException: Lines
	at io.hypersistence.utils.hibernate.util.ReflectionUtils.handleException(ReflectionUtils.java:674)
	at io.hypersistence.utils.hibernate.util.ReflectionUtils.getClass(ReflectionUtils.java:513)
	at io.hypersistence.utils.hibernate.type.array.internal.ListArrayTypeDescriptor.setParameterValues(ListArrayTypeDescriptor.java:119)
	at io.hypersistence.utils.hibernate.type.array.ListArrayType.setParameterValues(ListArrayType.java:43)
	at org.hibernate.mapping.MappingHelper.injectParameters(MappingHelper.java:70)
	at org.hibernate.mapping.BasicValue.setExplicitCustomType(BasicValue.java:843)
	at org.hibernate.cfg.annotations.BasicValueBinder.fillSimpleValue(BasicValueBinder.java:1238)
	at org.hibernate.cfg.SetBasicValueTypeSecondPass.doSecondPass(SetBasicValueTypeSecondPass.java:26)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1782)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1729)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:300)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1348)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1419)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:66)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	... 93 more
```

with the old *@Type(type = "json")* everything was working

**Comment by vladmihalcea** [comment]
[This test case](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-60/src/test/java/io/hypersistence/utils/hibernate/type/json/PostgreSQLJsonListEnumTest.java#L63) is very similar to yours and works just fine.

Try to run both in debug mode and see where they differ.

**Comment by CristianPi** [comment]
> [This test case](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-60/src/test/java/io/hypersistence/utils/hibernate/type/json/PostgreSQLJsonListEnumTest.java#L63) is very similar to yours and works just fine.
> 
> Try to run both in debug mode and see where they differ.

yes, i'm busy this week, going to reply the next one

**Comment by vladmihalcea** [comment]
Closed as no Pull Request was sent with the fix.
