### ISSUE TITLE
Receiver class io.hypersistence.utils.hibernate.type.basic.NullableCharacterType does not define or inherit an implementation of the resolved method 'org.hibernate.type.descriptor.jdbc.JdbcType getJdbcType()' of interface org.hibernate.type.BasicType.

### ISSUE THREAD

**Issue by mattiaskagstrom** [vladmihalcea/hypersistence-utils#626]
I got his error when trying to migrate from spring 2.7 to 3.0.
I have been unable to find anyone else with this problem, so it's most likely something I am doing wrong, and if so, I need some assistance on how to debug the issue.

versions:
Java 17.0.7
Hibernate Validator 8.0.0.Final
Spring Boot v3.0.6, Spring v6.0.8
Hibernate ORM core version 6.1.7.Final
Hibernate Commons Annotations {5.1.2.Final}
hypersistence-utils-hibernate-62 3.3.2

`[ERROR] 2023-05-03 13:01:20.236 [main] o.s.b.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxxEntityManagerFactory' defined in class path resource [com/company/system/domain/config/PersistanceConfiguration.class]: Receiver class io.hypersistence.utils.hibernate.type.basic.NullableCharacterType does not define or inherit an implementation of the resolved method 'org.hibernate.type.descriptor.jdbc.JdbcType getJdbcType()' of interface org.hibernate.type.BasicType.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1132)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:907)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
	at com.company.system.domain.xxxApplication.main(xxxxApplication.java:16)
Caused by: java.lang.AbstractMethodError: Receiver class io.hypersistence.utils.hibernate.type.basic.NullableCharacterType does not define or inherit an implementation of the resolved method 'org.hibernate.type.descriptor.jdbc.JdbcType getJdbcType()' of interface org.hibernate.type.BasicType.
	at org.hibernate.type.BasicTypeRegistry.applyOrOverwriteEntry(BasicTypeRegistry.java:252)
	at org.hibernate.type.BasicTypeRegistry.register(BasicTypeRegistry.java:239)
	at org.hibernate.type.BasicTypeRegistry.register(BasicTypeRegistry.java:223)
	at org.hibernate.boot.model.TypeContributions.contributeType(TypeContributions.java:56)
	at io.hypersistence.utils.hibernate.type.HibernateTypesContributor.contributeType(HibernateTypesContributor.java:118)
	at io.hypersistence.utils.hibernate.type.HibernateTypesContributor.contribute(HibernateTypesContributor.java:96)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:390)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:143)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1348)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1419)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:66)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	... 16 common frames omitted`

**Comment by vladmihalcea** [comment]
You're using the wrong Hypersistence Utils dependency.

ForHibernate ORM core version 6.1.7.Final, you need to use hypersistence-utils-hibernate-60.
