### ISSUE TITLE
JsonType fails for Map types without generic types 

### ISSUE THREAD

**Issue by snimavat** [vladmihalcea/hypersistence-utils#641]
When a field which is mapped to json type, is assigned a value of a `custom map type, which doesnt have generic types`
Trying to save the entity will fail with below error.

```
Caused by: java.lang.IllegalArgumentException: Cannot create TypeBindings for class org.grails.web.json.JSONObject with 2 type parameters: class expects 0
        at com.fasterxml.jackson.databind.type.TypeBindings.create(TypeBindings.java:139)
        at com.fasterxml.jackson.databind.type.TypeBindings.create(TypeBindings.java:98)
        at com.fasterxml.jackson.databind.type.TypeFactory.constructParametricType(TypeFactory.java:1008)
        at com.fasterxml.jackson.databind.type.TypeFactory.constructParametricType(TypeFactory.java:977)
        at io.hypersistence.utils.hibernate.type.util.ObjectMapperJsonSerializer.clone(ObjectMapperJsonSerializer.java:40)
        at io.hypersistence.utils.hibernate.type.util.ObjectMapperWrapper.clone(ObjectMapperWrapper.java:145)
        at io.hypersistence.utils.hibernate.type.json.internal.JsonTypeDescriptor$1.deepCopyNotNull(JsonTypeDescriptor.java:54)
        at org.hibernate.type.descriptor.java.MutableMutabilityPlan.deepCopy(MutableMutabilityPlan.java:35)
        at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:308)
        at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:304)
        at org.hibernate.type.TypeHelper.deepCopy(TypeHelper.java:55)
```

I am using JsonType with Grails. One of the field  of type Map in my entity class is mapped to `JsonType` Every thing works fine during tests and when a HashMap or LinkedHashMap etc are assigned 

However, when a custom implementation of Map - eg [Grails JSON Object](http://docs.grails.org/3.1.2/api/org/grails/web/json/JSONObject.html) which implents map (but does not have generic types) is assigned to the field. Trying to save the object would fail with above error.

The problem is with `ObjectMapperSerializer` which fails if the Map implementation does not have Generic types

[Here's the problamatic code](https://github.com/vladmihalcea/hypersistence-utils/blob/aae7cebd612f0c6fc41b7b0c84e36aedc835dfb6/hypersistence-utils-hibernate-5/src/main/java/io/hypersistence/utils/hibernate/type/util/ObjectMapperJsonSerializer.java#L40)

I am on Hibernate 5.4 version of the hypersistance-utils

**Comment by vladmihalcea** [comment]
@snimavat Try to debug it and investigate what causes the issue and how it could be prevented. 
Once you have a replicating test case and a fix proposal, send me a Pull Request so that I can review it. Looking forward to your contribution.

**Comment by snimavat** [comment]
I will reproduce it in tests of this project itself.

**Comment by vladmihalcea** [comment]
You can try with a non-generic `Map` or a class that extends one such Map.

**Comment by vladmihalcea** [comment]
Closed as no Pull Request was provided to replicate the issue.
