### ISSUE TITLE
@Enumerated enum field mapping failing after migrating to Hibernate 6 

### ISSUE THREAD

**Issue by dsu** [vladmihalcea/hypersistence-utils#642]
Hi,
We have migrated our projects to Spring Boot 3/Hibernate 6 and hypersistence-utils-hibernate-60:3.3.2.
I have tried to test with latest version of hypersistence-utils but there is still similar issue, but with a different error message.

The problem is related only to one specific enum.
For example, we have this query:

```java
@Query(value = """
    select distinct u from UserView u
    left join UserAssignment g ON u.id = g.userId
    where (:#{#accessFilterParameters.root} = true or g.groupId in (:#{#accessFilterParameters.accessibleGroups}))
    and (:#{#userSearchParameters.simsId} = NULL OR upper(u.simsId) like %:#{#userSearchParameters.simsId?.toUpperCase()}%)
    and (:#{#userSearchParameters.userType} = NULL OR u.userType = :#{#userSearchParameters.userType})
    and (:#{#userSearchParameters.username} = NULL OR UPPER(u.username) LIKE %:#{#userSearchParameters.username?.toUpperCase()}%)
    and (u.active = true OR :#{#userSearchParameters.showDeactivated} = true)
    """)
List<IdProjection> searchIds(@Param("accessFilterParameters") AccessFilterParameters accessFilterParameters,
    @Param("userSearchParameters") UserSearchParameters userSearchParameters, Pageable pageable); 
```

the generated queries looks OK:
```sql
 select distinct u1_0.id,u1_0.active,u1_0.default_user_group_id_for_shipment_creation,u1_0.sims_id,u1_0.type,u1_0.username from public.iot_user u1_0 left join public.iot_user_assignment u2_0 on u1_0.id=u2_0.user_id where (?=true or u2_0.group_id in (?,?,?,?)) and (? is null or upper(u1_0.sims_id) like ? escape '') and (? is null or u1_0.type=?) and (? is null or upper(u1_0.username) like ? escape '') and (u1_0.active=true or ?=true) order by u1_0.sims_id offset ? rows fetch first ? rows only 
```

The field mapping:

```java
@Column(name = "type")
@Enumerated(EnumType.STRING)
private UserType userType;
```
This field name is "type", I wonder if that may cause some issues. UserType is just an Enum.

And when we ran the query it has some problems with mapping this field (or argument of type UserType used in the query):

```java
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "this.enumClass" is null
 
                at org.hibernate.type.EnumType.verifyConfigured(EnumType.java:386)
                at org.hibernate.type.EnumType.nullSafeSet(EnumType.java:392)
                at io.hypersistence.utils.hibernate.type.basic.PostgreSQLEnumType.set(PostgreSQLEnumType.java:70)
                at io.hypersistence.utils.hibernate.type.basic.PostgreSQLEnumType.set(PostgreSQLEnumType.java:29)
                at io.hypersistence.utils.hibernate.type.ImmutableType.nullSafeSet(ImmutableType.java:103)
                at org.hibernate.type.internal.UserTypeSqlTypeAdapter$ValueBinderImpl.bind(UserTypeSqlTypeAdapter.java:183)
                at org.hibernate.sql.exec.internal.AbstractJdbcParameter.bindParameterValue(AbstractJdbcParameter.java:118)
                at org.hibernate.sql.exec.internal.AbstractJdbcParameter.bindParameterValue(AbstractJdbcParameter.java:108)
                at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.bindParameters(DeferredResultSetAccess.java:199)
                at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:228)
                at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:163)
                at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:254)
                at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:134)
                at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)
                at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)
                at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:178)
                at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
                at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:361)
                at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:168)
                at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:93)
                at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
                at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$0(ConcreteSqmSelectQueryPlan.java:110)
                at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:303)
                at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:244)
                at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:518)
                at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:367)
                at org.hibernate.query.Query.getResultList(Query.java:119)
                at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:127)
                at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:90)
                at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:148)
                at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136)
                at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
                at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
                at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
                at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:77)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
                at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
                at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:134)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
                at xxx.$Proxy278.searchIds(Unknown Source)
                at xxx.view.user.SearchUserMixin.search(SearchUserMixin.java:22)

```

When updating lib to 3.4.4

```java
java.lang.NullPointerException: Cannot invoke "org.hibernate.metamodel.mapping.JdbcMapping.getJdbcValueBinder()" because "jdbcMapping" is null
 
                at org.hibernate.sql.exec.internal.AbstractJdbcParameter.bindParameterValue(AbstractJdbcParameter.java:118)
                at org.hibernate.sql.exec.internal.AbstractJdbcParameter.bindParameterValue(AbstractJdbcParameter.java:108)
                at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.bindParameters(DeferredResultSetAccess.java:199)
                at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:228)
                at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:163)
                at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:254)
                at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:134)
                at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)
                at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)
                at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:178)
                at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
                at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:361)
                at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:168)
                at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:93)
                at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
                at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$0(ConcreteSqmSelectQueryPlan.java:110)
                at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:303)
                at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:244)
                at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:518)
                at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:367)
                at org.hibernate.query.Query.getResultList(Query.java:119)
                at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:127)
                at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:90)
                at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:148)
                at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136)
                at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
                at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
                at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
                at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:77)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
                at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
                at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:134)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
                at xxxx.$Proxy278.searchIds(Unknown Source)


```
I have tried native query, custom types, custom converters. It didn't solve the problem. I had to map userType to `String`.

**Comment by vladmihalcea** [comment]
Check out [this test case](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-60/src/test/java/io/hypersistence/utils/hibernate/type/basic/PostgreSQLEnumTest.java) and see why my test works while your apo is failing.

**Comment by dsu** [comment]
Hi, My case is different.
I don't want to map this field to the ENUM type. The field should be mapped to a varchar. I am not adding @Type(PostgreSQLEnumType.class) to the field definition.

**Comment by vladmihalcea** [comment]
In that case, you should disable the `PostgreSQLEnumType` from being auto-registered, as explained by [this article](https://vladmihalcea.com/customize-hibernatetypescontributor-hypersistence-utils/).

**Comment by vladmihalcea** [comment]
Closed as no Pull Request was provided to try to replicate the issue using the existing test cases.
