### ISSUE TITLE
hibernate-62-Property 'xxx' is mapped as basic aggregate component array, but this is not yet supported.

### ISSUE THREAD

**Issue by soupedog** [vladmihalcea/hypersistence-utils#643]
Hi team,

I recently upgraded my application from
 ``jdk 8, hibernate-types-55, hibernate 5`` 
to 
``jdk 17, hypersistence-utils-hibernate-62, hibernate 6 ``

Although it worked fine before the upgrade, after the upgrade I found that I couldn't use a list of custom Java class as a field in a persistent object anymore.

Here is my PO:

```java
@Getter
@Setter
@Builder
@Generated
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@Embeddable
public class CategoryAccessRule {
    @Column(columnDefinition = "enum ('PERSONAL', 'SECRET_KEY', 'GROUP', 'MALE', 'FEMALE', 'CRON', 'PUBLIC') default 'PERSONAL'")
    @Enumerated(EnumType.STRING)
    private AccessRuleTypeEnum accessRuleType;
    @Column
    private boolean requirement;
    @Column
    private String extendString;
}
```

```java
@Getter
@Setter
@Builder
@Generated
@NoArgsConstructor
@AllArgsConstructor
@Entity
@DynamicInsert
@DynamicUpdate
@Table(name = "category", indexes = {@Index(name = "index_cid", columnList = "cid", unique = true)})
public class Category extends BasePo {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column
    private Integer categoryId;
    @Column(nullable = false)
    private String cid;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, columnDefinition = "enum ('DEFAULT', 'PATH') default 'DEFAULT'")
    private CategoryTypeEnum categoryType;
    @Type(JsonStringType.class)
    @Column(columnDefinition = "json")
    private List<CategoryAccessRule> accessRuleList;
……
}
```

Here is the error log I get:
```
Caused by: org.hibernate.AnnotationException: Property 'xxxx.xxxx.po.Category.accessRuleList' is mapped as basic aggregate component array, but this is not yet supported.
	at org.hibernate.boot.model.internal.PropertyBinder.bindBasic(PropertyBinder.java:1043) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.boot.model.internal.PropertyBinder.bindProperty(PropertyBinder.java:867) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.boot.model.internal.PropertyBinder.buildProperty(PropertyBinder.java:765) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.boot.model.internal.PropertyBinder.processElementAnnotations(PropertyBinder.java:686) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.boot.model.internal.EntityBinder.processIdPropertiesIfNotAlready(EntityBinder.java:967) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.boot.model.internal.EntityBinder.handleIdentifier(EntityBinder.java:302) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.boot.model.internal.EntityBinder.bindEntityClass(EntityBinder.java:228) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.boot.model.internal.AnnotationBinder.bindClass(AnnotationBinder.java:417) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:255) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:275) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:318) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1380) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1451) ~[hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:75) ~[spring-orm-6.0.10.jar:6.0.10]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[spring-orm-6.0.10.jar:6.0.10]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[spring-orm-6.0.10.jar:6.0.10]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[spring-orm-6.0.10.jar:6.0.10]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352) ~[spring-orm-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[spring-beans-6.0.10.jar:6.0.10]
	... 114 common frames omitted
```

Also, I noticed that ``org.hibernate.boot.model.internal.PropertyBinder``  line 1038

```java
else if ( property.isCollection() && property.getElementClass() != null
		&& isEmbedded( property, property.getElementClass() ) ) {
	// This is a special kind of basic aggregate component array type
	// todo: see HHH-15830
	throw new AnnotationException(
			"Property '" + BinderHelper.getPath( propertyHolder, inferredData )
					+ "' is mapped as basic aggregate component array, but this is not yet supported."
	);
}
```

**What I'd like to ask are:**
- What is "HHH-15830" ?
- Is there somewhere I can look up what ``HHH-15830`` is?
-  Will custom type lists be supported in some future release?

**Comment by vladmihalcea** [comment]
@soupedog I won't have any spare time to work on this framework in the next 1-2 years, so feel free to investigate the issue and submit a Pull Request with a fix. I will check the Pull Requests from time to time and see whether they can be integrated.

Or, if your company is interested in [paying for the development of this feature](https://vladmihalcea.com/consulting/), let me know and we can do it via a B2B contract.

**Comment by soupedog** [comment]
Got it. Thanks for your reply.
