### ISSUE TITLE
CastClass Exception After migrating to Hibernate 6. 

### ISSUE THREAD

**Issue by saga10** [vladmihalcea/hypersistence-utils#645]
```
2023-07-25T18:02:51.451Z  INFO 1 --- [mirai-tp-3] o.h.e.internal.DefaultLoadEventListener  : HHH000327: Error performing load 
command 
org.hibernate.HibernateException: Unable to extract JDBC value for position `134`
at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.readCurrentRowValues(JdbcValuesResultSetImpl.java:271)
at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advance(JdbcValuesResultSetImpl.java:244)
at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:85)
at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:29)
at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:88)
at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:177)
at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:443)
at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:166)
at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:91)
at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
at org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:140)
at org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:110)
at org.hibernate.loader.ast.internal.SingleIdEntityLoaderStandardImpl.load(SingleIdEntityLoaderStandardImpl.java:72)
at org.hibernate.persister.entity.AbstractEntityPersister.doLoad(AbstractEntityPersister.java:4416)
at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4406)
at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:590)
at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:563)
at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:221)
at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:358)
at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:110)
at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:72)
at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118)
at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1244)
at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1232)
at org.hibernate.loader.access.IdentifierLoadAccessImpl.doLoad(IdentifierLoadAccessImpl.java:195)
at org.hibernate.loader.access.IdentifierLoadAccessImpl.lambda$load$1(IdentifierLoadAccessImpl.java:161)
at org.hibernate.loader.access.IdentifierLoadAccessImpl.perform(IdentifierLoadAccessImpl.java:108)
at org.hibernate.loader.access.IdentifierLoadAccessImpl.load(IdentifierLoadAccessImpl.java:161)
at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2336)
at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2303)
at jdk.internal.reflect.GeneratedMethodAccessor173.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:311)
at jdk.proxy3/jdk.proxy3.$Proxy273.find(Unknown Source)
at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findById(SimpleJpaRepository.java:307)
at jdk.internal.reflect.GeneratedMethodAccessor168.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:288)
at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516)
at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168)
at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:72)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:164)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:244)
at jdk.proxy3/jdk.proxy3.$Proxy316.findById(Unknown Source)
at com.asml.mirai.libraries.entity.service.EntityServiceDefaultInterface.findById(EntityServiceDefaultInterface.java:527)
at com.asml.mirai.libraries.entity.service.EntityServiceDefaultInterface.getEntityById(EntityServiceDefaultInterface.java:552)
at com.asml.mirai.libraries.entity.service.EntityServiceDefaultInterface.lambda$filter$12(EntityServiceDefaultInterface.java:493)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.base/java.util.ArrayList$Itr.forEachRemaining(Unknown Source)
at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
at com.asml.mirai.libraries.entity.service.EntityServiceDefaultInterface.filter(EntityServiceDefaultInterface.java:495)
at com.asml.mirai.libraries.entity.service.EntityServiceDefaultInterface.filter(EntityServiceDefaultInterface.java:500)
at com.asml.mirai.libraries.entity.service.EntityServiceDefaultInterface.getAllByParent(EntityServiceDefaultInterface.java:607)
at jdk.internal.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
at com.asml.mirai.mychange.changerequestservice.customerimpact.service.CustomerImpactService$SpringCGLIB$0.getAllByParent(<generated>)
at com.asml.mirai.mychange.changerequestservice.core.component.AggregateBuilder.deriveRelatedEntityFromBaseEntityInterfaceId(AggregateBuilder.java:303)
at com.asml.mirai.mychange.changerequestservice.core.component.AggregateBuilder.getRelatedEntity(AggregateBuilder.java:237)
at com.asml.mirai.mychange.changerequestservice.core.component.AggregateBuilder.processAggregates(AggregateBuilder.java:158)
at com.asml.mirai.mychange.changerequestservice.core.component.AggregateBuilder.buildAggregate(AggregateBuilder.java:61)
at com.asml.mirai.mychange.changerequestservice.core.component.AggregateBuilder.processAggregates(AggregateBuilder.java:178)
at com.asml.mirai.mychange.changerequestservice.core.component.AggregateBuilder.buildAggregate(AggregateBuilder.java:61)
at com.asml.mirai.libraries.entity.service.EntityServiceDefaultInterface.getAggregate(EntityServiceDefaultInterface.java:685)
at com.asml.mirai.mychange.changerequestservice.changerequest.service.ChangeRequestService.getAggregate(ChangeRequestService.java:1539)
at jdk.internal.reflect.GeneratedMethodAccessor197.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
at com.asml.mirai.mychange.changerequestservice.changerequest.service.ChangeRequestService$SpringCGLIB$0.getAggregate(<generated>)
at com.asml.mirai.mychange.changerequestservice.changerequest.service.ChangeRequestEvaluationContext.setAggregate(ChangeRequestEvaluationContext.java:41)
at com.asml.mirai.mychange.changerequestservice.changerequest.service.ChangeRequestEvaluationContext.getAggregate(ChangeRequestEvaluationContext.java:33)
at com.asml.mirai.mychange.changerequestservice.changerequest.service.ChangeRequestEvaluationContext.isChangeRequestTypeIsAdministrativeHierarchy(ChangeRequestEvaluationContext.java:81)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:139)
at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:139)
at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:95)
at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:212)
at org.springframework.expression.spel.ast.OperatorNot.getValueInternal(OperatorNot.java:47)
at org.springframework.expression.spel.ast.OperatorNot.getValueInternal(OperatorNot.java:36)
at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:212)
at org.springframework.expression.spel.ast.OpAnd.getBooleanValue(OpAnd.java:57)
at org.springframework.expression.spel.ast.OpAnd.getValueInternal(OpAnd.java:52)
at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:114)
at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:207)
at com.asml.mirai.libraries.security.core.component.CaseActionList.lambda$getCaseActions$3(CaseActionList.java:133)
at java.base/java.lang.Iterable.forEach(Unknown Source)
at com.asml.mirai.libraries.security.core.component.CaseActionList.getCaseActions(CaseActionList.java:122)
at com.asml.mirai.libraries.security.core.service.SecurityServiceDefaultInterface.getCaseActions(SecurityServiceDefaultInterface.java:181)
at com.asml.mirai.libraries.security.core.service.SecurityServiceDefaultInterface.lambda$getCasePermissions$4(SecurityServiceDefaultInterface.java:362)
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:94)
at io.micrometer.context.ContextSnapshot.lambda$wrap$0(ContextSnapshot.java:91)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class [B cannot be cast to class org.postgresql.util.PGInterval ([B is in module java.base of loader 'bootstrap'; org.postgresql.util.PGInterval is in unnamed module of loader 'app')
at io.hypersistence.utils.hibernate.type.interval.PostgreSQLPeriodType.get(PostgreSQLPeriodType.java:37)
at io.hypersistence.utils.hibernate.type.interval.PostgreSQLPeriodType.get(PostgreSQLPeriodType.java:23)
at io.hypersistence.utils.hibernate.type.ImmutableType.nullSafeGet(ImmutableType.java:98)
at org.hibernate.type.internal.UserTypeSqlTypeAdapter$ValueExtractorImpl.extract(UserTypeSqlTypeAdapter.java:110)
at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.readCurrentRowValues(JdbcValuesResultSetImpl.java:263)
... 138 common frames omitted
```

**Comment by vladmihalcea** [comment]
As explained in the [README](https://github.com/vladmihalcea/hypersistence-utils#bug-fixes-and-enhancements), I no longer offer free support for this project.

Unless your company is interested in paying for support, you will have to investigate and fix the problem and send a Pull Request with the fix.

**Comment by vladmihalcea** [comment]
@saga10 If you wish to fix this issue, here's what you need to do:

- create a replicating test case that proves the problem
- change the library so that the issue is fixed and your test passes
- send me a Pull Request with the test case and the fix 

If no Pull Request is sent in the next 4 weeks, the issue will be closed.
