### ISSUE TITLE
Hibernate 6.3 support?

### ISSUE THREAD

**Issue by oliveryasuna** [vladmihalcea/hypersistence-utils#651]
We would like to upgrade from Hibernate 6.2.5 to 6.3.0. Is there planned support in the near future. Tried using `hypersistence-utils-hibernate-62:3.5.2`, but got an exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/hibernate/type/descriptor/converter/spi/EnumValueConverter
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
	at org.hibernate.internal.util.ReflectHelper.getConstructor(ReflectHelper.java:369)
	at org.hibernate.boot.model.TypeBeanInstanceProducer.produceBeanInstance(TypeBeanInstanceProducer.java:36)
	at org.hibernate.boot.model.TypeBeanInstanceProducer.produceBeanInstance(TypeBeanInstanceProducer.java:63)
	at org.hibernate.resource.beans.container.spi.FallbackContainedBean.<init>(FallbackContainedBean.java:28)
	at org.hibernate.resource.beans.internal.ManagedBeanRegistryImpl.getBean(ManagedBeanRegistryImpl.java:107)
	at org.hibernate.mapping.BasicValue.getUserTypeBean(BasicValue.java:875)
	at org.hibernate.mapping.BasicValue.getConfiguredUserTypeBean(BasicValue.java:848)
	at org.hibernate.mapping.BasicValue.setExplicitCustomType(BasicValue.java:823)
	at org.hibernate.boot.model.internal.BasicValueBinder.fillSimpleValue(BasicValueBinder.java:1381)
	at org.hibernate.boot.model.internal.SetBasicValueTypeSecondPass.doSecondPass(SetBasicValueTypeSecondPass.java:27)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1815)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1762)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:331)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1404)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1475)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:55)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at com.sferion.planglobal.misc.MyPersistenceModule.buildEntityManagerFactory(MyPersistenceModule.java:118)
	at com.sferion.planglobal.misc.MyPersistenceModule$1.configurePersistence(MyPersistenceModule.java:55)
	at com.sferion.planglobal.backend.onamipersist.PersistenceModule.configurePersistenceUnits(PersistenceModule.java:72)
	at com.sferion.planglobal.backend.onamipersist.PersistenceModule.configure(PersistenceModule.java:59)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:64)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:426)
	at com.google.inject.AbstractModule.install(AbstractModule.java:106)
	at com.sferion.planglobal.misc.MyPersistenceModule.configure(MyPersistenceModule.java:50)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:64)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:426)
	at com.google.inject.spi.Elements.getElements(Elements.java:113)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at com.sferion.planglobal.misc.guice.server.GuiceVaadinServlet.init(GuiceVaadinServlet.java:161)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.initServlet(ServletHolder.java:637)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.getServlet(ServletHolder.java:495)
	at com.sferion.planglobal.App$1.lifeCycleStarted(App.java:83)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarted(AbstractLifeCycle.java:253)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:94)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:615)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:466)
	at org.eclipse.jetty.server.Server.doStart(Server.java:556)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at com.sferion.planglobal.App.main(App.java:123)
Caused by: java.lang.ClassNotFoundException: org.hibernate.type.descriptor.converter.spi.EnumValueConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 50 more
```

Exception makes sense, since the class doesn't exist in 6.3.0.

**Comment by vladmihalcea** [comment]
Looking forward to getting your Pull Request that addresses this issue.

**Comment by oliveryasuna** [comment]
@vladmihalcea Thanks for the response, but I am not going to open a PR. We are moving away from Hibernate anyway and I do not have the time to fix this.

**Comment by vladmihalcea** [comment]
@oliveryasuna I'll close this issue for now and will reopen it once someone provides a fix to it.
