### ISSUE TITLE
Version to use with Hibernate 5 Jakarta artifact

### ISSUE THREAD

**Issue by amy-b-cheng** [vladmihalcea/hypersistence-utils#720]
I'm migrating my application from using javax to jakarta, and currently on Hibernate 5. I changed my hibernate dependency to org.hibernate:hibernate-core-jakarta:5.6.15.Final, but I'm getting this error when creating a Guice injector:

` Caused by: 
 java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement
at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:137)
at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:124)
at com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule.setupModule(JaxbAnnotationModule.java:98)
at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:908)
at com.fasterxml.jackson.databind.ObjectMapper.registerModules(ObjectMapper.java:1110)
at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1194)
at io.hypersistence.utils.hibernate.type.util.ObjectMapperWrapper.<clinit>(ObjectMapperWrapper.java:29)
at io.hypersistence.utils.hibernate.type.util.JsonConfiguration.<init>(JsonConfiguration.java:45)
at io.hypersistence.utils.hibernate.type.util.JsonConfiguration.<init>(JsonConfiguration.java:21)
at io.hypersistence.utils.hibernate.type.util.JsonConfiguration.<clinit>(JsonConfiguration.java:16)
at io.hypersistence.utils.hibernate.type.json.JsonBinaryType.<init>(JsonBinaryType.java:36)
at io.hypersistence.utils.hibernate.type.json.JsonBinaryType.<clinit>(JsonBinaryType.java:33)
at io.hypersistence.utils.hibernate.type.HibernateTypesContributor.contribute(HibernateTypesContributor.java:115)
at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:391)
at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:132)
at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)`

For Hibernate 5 using Jakarta, am I meant to be using the hypersistence-utils-hibernate-60 or hypersistence-utils-hibernate-55 artifact? And follow up, am I meant to be declaring as a dependency jackson-module-jakarta-xmlbind-annotations (in the README, this is for Hibernate 6) or jackson-databind + jackson-module-jaxb-annotations (for Hibernate 5)?

**Comment by vladmihalcea** [comment]
The library only supports Jakarta Persistence from Hibernate 6 onwards. So, either you use Hibernate 6 with the appropriate `hypersistence-utils-hibernate-6x` module or you use Hibernate 5 with `javax.persistence` and the appropriate `hypersistence-utils-hibernate-5x`.

The `org.hibernate:hibernate-core-jakarta:5.6.15` is not and will never be supported by Hypersistence Utils.
