### ISSUE TITLE
Array mapping examples throw validation exceptions

### ISSUE THREAD

**Issue by ctmay4** [vladmihalcea/hypersistence-utils#741]
**Describe the bug**

Trying to follow the page https://vladmihalcea.com/postgresql-array-java-list/ for mapping Postgres arrays. The example on that page looks like this:

```java
    @Type(ListArrayType.class)
    @Column(
        name = "sensor_names",
        columnDefinition = "text[]"
    )
    private List<String> sensorNames;
```

The field is defined like this:

```sql
non_prop_name text[]
```

The entity is defined just like the page above described:

```java
    @Type(ListArrayType.class)
    @Column(
            name = "non_prop_name",
            columnDefinition = "text[]"
    )
    private List<String> nonProprietaryName;
```

Hibernate fails to initialize with the following error:

```
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [non_prop_name] in table [ndc]; found [_text (Types#ARRAY)], but expecting [text[] (Types#OTHER)]
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateColumnType(AbstractSchemaValidator.java:168)
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:155)
	at org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:46)
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:98)
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:76)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:289)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:144)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:141)
	at org.hibernate.boot.internal.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:37)
	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:322)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:457)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1506)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:75)
```

**Additional context**

My application was working fine using a `@Converter` before. It looked like this:

```java
@Converter
public class StringArrayToListConverter implements AttributeConverter<List<String>, String[]> {

    @Override
    public String[] convertToDatabaseColumn(List<String> attribute) {
        if (attribute == null || attribute.isEmpty())
            return null;
        return attribute.toArray(new String[0]);
    }

    @Override
    public List<String> convertToEntityAttribute(String[] dbData) {
        if (dbData == null || dbData.length == 0)
            return null;
        return Arrays.stream(dbData).collect(Collectors.toList());
    }
}
```

```java
    @Column(name = "non_prop_name")
    @Convert(converter = StringArrayToListConverter.class)
    private List<String> nonProprietaryName;
```

However while I had Postgres 14 installed locally which worked fine, when I deployed it to a server with Postgres 16, I got errors that looked like this:

```
Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is java.lang.ClassCastException: class org.hibernate.type.internal.CustomMutabilityConvertedBasicTypeImpl cannot be cast to class org.hibernate.type.BasicPluralType (org.hibernate.type.internal.CustomMutabilityConvertedBasicTypeImpl and org.hibernate.type.BasicPluralType are in unnamed module of loader org.springframework.boot.loader.launch.LaunchedClassLoader @f6f4d33)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:421)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:366)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802)
        ... 114 common frames omitted
Caused by: java.lang.ClassCastException: class org.hibernate.type.internal.CustomMutabilityConvertedBasicTypeImpl cannot be cast to class org.hibernate.type.BasicPluralType (org.hibernate.type.internal.CustomMutabilityConvertedBasicTypeImpl and org.hibernate.type.BasicPluralType are in unnamed module of loader org.springframework.boot.loader.launch.LaunchedClassLoader @f6f4d33)
```

That led me to follow the instructions in the project for mapping array types. I am already using the library to map JSONB fields.

I am using Spring Boot 3.3.2, Hibernate 6.5 and Postgres 14. Also the following version of the library.

```
<dependency>
    <groupId>io.hypersistence</groupId>
    <artifactId>hypersistence-utils-hibernate-63</artifactId>
    <version>3.8.2</version>
</dependency>
```

**Comment by ctmay4** [comment]
I found a way to get my code to work under Postgres 16. I'll leave this here in case it helps anyone.

I removed all my `@Converter` annotations. I stopped using custom user types.

For simple lists of String, I just use this:

```java
@Column(name = "non_prop_name")
@JdbcTypeCode(SqlTypes.ARRAY)
private List<String> nonProprietaryName;
```

For lists of enums:

```java
@Column(name = "edit_roles", columnDefinition = "varchar[]")
@JdbcTypeCode(SqlTypes.ARRAY)
@Enumerated(EnumType.STRING)
private List<Role> editRoles;
```

I guess Hibernate supports this out of the box now. Much cleaner and more importantly it works!
